In [1]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

In [4]:
# Project Root
PROJECT_ROOT = Path("..")

RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"

PROCESSED_DATA.mkdir(parents=True, exist_ok=True)

CSV_PATH = r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\Raw\bhagavad_gita.csv"

In [5]:
df = pd.read_csv(CSV_PATH)

print("Dataset Loaded Successfully")
print("="*50)
print(df.shape)

df.head()

Dataset Loaded Successfully
==================================================
(657, 5)

,unique_key,sanskrit_data,translation,minilm_embedding,bge_embedding
0,1,धृतराष्ट्र उवाचधर्मक्षेत्रे कुरुक्षेत्रे समवेत...,Bhagavad-gītā is the widely read theistic scie...,[-5.24128601e-02 -4.30841483e-02 -6.47022948e-...,[-0.01605505 -0.02675599 0.03172645 ... 0.01...
1,2,सञ्जय उवाचदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्य...,Dhṛtarāṣṭra was blind from birth. Unfortunatel...,[-4.69386727e-02 7.47326240e-02 -3.58456410e-...,[ 0.00271094 -0.02861168 -0.00402028 ... -0.01...
2,3,पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ।व्...,"Duryodhana, a great diplomat, wanted to point ...",[-5.85098304e-02 7.82331526e-02 -4.19250280e-...,[ 0.00756507 0.00059658 0.0014121 ... 0.01...
3,4,अत्र श‍ूरा महेष्वासा भीमार्जुनसमा युधि ।युयुधा...,Even though Dhṛṣṭadyumna was not a very import...,[ 3.46771814e-02 5.77217601e-02 -6.88736280e-...,[ 0.01461127 -0.00751154 -0.00647122 ... 0.01...
4,5,धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान् ।पुरु...,"There are also great heroic, powerful fighters...",[-4.22634790e-03 -4.42187884e-04 -1.04459047e-...,[ 0.01745811 0.0102712 0.00768196 ... -0.00...

In [6]:
print("Columns")
print(df.columns.tolist())

print("\nDataset Info")
print(df.info())

Columns
['unique_key', 'sanskrit_data', 'translation', 'minilm_embedding', 'bge_embedding']

Dataset Info
<class 'pandas.DataFrame'>
RangeIndex: 657 entries, 0 to 656
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   unique_key        657 non-null    int64
 1   sanskrit_data     657 non-null    str
 2   translation       657 non-null    str
 3   minilm_embedding  657 non-null    str
 4   bge_embedding     657 non-null    str
dtypes: int64(1), str(4)
memory usage: 5.2 MB
None

In [7]:
required_columns = [
    "unique_key",
    "sanskrit_data",
    "translation"
]

df = df[required_columns]

df.head()

,unique_key,sanskrit_data,translation
0,1,धृतराष्ट्र उवाचधर्मक्षेत्रे कुरुक्षेत्रे समवेत...,Bhagavad-gītā is the widely read theistic scie...
1,2,सञ्जय उवाचदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्य...,Dhṛtarāṣṭra was blind from birth. Unfortunatel...
2,3,पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ।व्...,"Duryodhana, a great diplomat, wanted to point ..."
3,4,अत्र श‍ूरा महेष्वासा भीमार्जुनसमा युधि ।युयुधा...,Even though Dhṛṣṭadyumna was not a very import...
4,5,धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान् ।पुरु...,"There are also great heroic, powerful fighters..."

In [8]:
print("Before:", len(df))

df = df.drop_duplicates()

print("After :", len(df))

Before: 657
After : 657

In [9]:
df = df.dropna()

print(df.shape)

(657, 3)

In [10]:
def clean_sanskrit(text):
    if pd.isna(text):
        return ""

    text = str(text)

    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()


def clean_translation(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.replace("\n", " ")
    text = text.replace("\t", " ")

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [11]:
df["sanskrit_data"] = df["sanskrit_data"].apply(clean_sanskrit)

df["translation"] = df["translation"].apply(clean_translation)

In [12]:
df.head()

,unique_key,sanskrit_data,translation
0,1,धृतराष्ट्र उवाचधर्मक्षेत्रे कुरुक्षेत्रे समवेत...,Bhagavad-gītā is the widely read theistic scie...
1,2,सञ्जय उवाचदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्य...,Dhṛtarāṣṭra was blind from birth. Unfortunatel...
2,3,पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ।व्...,"Duryodhana, a great diplomat, wanted to point ..."
3,4,अत्र श‍ूरा महेष्वासा भीमार्जुनसमा युधि ।युयुधा...,Even though Dhṛṣṭadyumna was not a very import...
4,5,धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान् ।पुरु...,"There are also great heroic, powerful fighters..."

In [13]:
documents = []

for _, row in df.iterrows():

    document = f"""
Verse ID: {row.unique_key}

Sanskrit:
{row.sanskrit_data}

Translation:
{row.translation}
"""

    documents.append(document.strip())

df["document"] = documents

In [14]:
print(df["document"].iloc[0])

Verse ID: 1

Sanskrit:
धृतराष्ट्र उवाचधर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सव: ।मामका: पाण्डवाश्चैव किमकुर्वत सञ्जय ॥ १ ॥

Translation:
Bhagavad-gītā is the widely read theistic science summarized in the Gītā-māhātmya ( Glorification of the Gītā ). There it says that one should read Bhagavad-gītā very scrutinizingly with the help of a person who is a devotee of Śrī Kṛṣṇa and try to understand it without personally motivated interpretations. The example of clear understanding is there in the Bhagavad-gītā itself, in the way the teaching is understood by Arjuna, who heard the Gītā directly from the Lord. If someone is fortunate enough to understand the Bhagavad-gītā in that line of disciplic succession, without motivated interpretation, then he surpasses all studies of Vedic wisdom, and all scriptures of the world. One will find in the Bhagavad-gītā all that is contained in other scriptures, but the reader will also find things which are not to be found elsewhere. That is the specific standard of the Gītā. It is the perfect theistic science because it is directly spoken by the Supreme Personality of Godhead, Lord Śrī Kṛṣṇa. The topics discussed by Dhṛtarāṣṭra and Sañjaya, as described in the Mahābhārata, form the basic principle for this great philosophy. It is understood that this philosophy evolved on the Battlefield of Kurukṣetra, which is a sacred place of pilgrimage from the immemorial time of the Vedic age. It was spoken by the Lord when He was present personally on this planet for the guidance of mankind. The word dharma-kṣetra (a place where religious rituals are performed) is significant because, on the Battlefield of Kurukṣetra, the Supreme Personality of Godhead was present on the side of Arjuna. Dhṛtarāṣṭra, the father of the Kurus, was highly doubtful about the possibility of his sons’ ultimate victory. In his doubt, he inquired from his secretary Sañjaya, “What did they do?” He was confident that both his sons and the sons of his younger brother Pāṇḍu were assembled in that Field of Kurukṣetra for a determined engagement of the war. Still, his inquiry is significant. He did not want a compromise between the cousins and brothers, and he wanted to be sure of the fate of his sons on the battlefield. Because the battle was arranged to be fought at Kurukṣetra, which is mentioned elsewhere in the Vedas as a place of worship – even for the denizens of heaven – Dhṛtarāṣṭra became very fearful about the influence of the holy place on the outcome of the battle. He knew very well that this would influence Arjuna and the sons of Pāṇḍu favorably, because by nature they were all virtuous. Sañjaya was a student of Vyāsa, and therefore, by the mercy of Vyāsa, Sañjaya was able to envision the Battlefield of Kurukṣetra even while he was in the room of Dhṛtarāṣṭra. And so, Dhṛtarāṣṭra asked him about the situation on the battlefield. Both the Pāṇḍavas and the sons of Dhṛtarāṣṭra belong to the same family, but Dhṛtarāṣṭra’s mind is disclosed herein. He deliberately claimed only his sons as Kurus, and he separated the sons of Pāṇḍu from the family heritage. One can thus understand the specific position of Dhṛtarāṣṭra in his relationship with his nephews, the sons of Pāṇḍu. As in the paddy field the unnecessary plants are taken out, so it is expected from the very beginning of these topics that in the religious field of Kurukṣetra, where the father of religion, Śrī Kṛṣṇa, was present, the unwanted plants like Dhṛtarāṣṭra’s son Duryodhana and others would be wiped out and the thoroughly religious persons, headed by Yudhiṣṭhira, would be established by the Lord. This is the significance of the words dharma-kṣetre and kuru-kṣetre, apart from their historical and Vedic importance.

Save Clean Dataset

In [15]:
clean_path = r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\processed\cleaned_dataset.csv"

df.to_csv(clean_path, index=False)

print("Saved:", clean_path)

Saved: C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\processed\cleaned_dataset.csv

Save Documents Only

In [16]:
documents_df = df[["unique_key", "document"]]

documents_path = r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\processed\documents.csv"

documents_df.to_csv(documents_path, index=False)

print("Saved:", documents_path)

Saved: C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\processed\documents.csv

Dataset Statistics

In [18]:
print("Final Dataset Statistics")

print("Total Documents :", len(df))

print("Average Sanskrit Length :",
      df["sanskrit_data"].str.len().mean())

print("Average Translation Length :",
      df["translation"].str.len().mean())

print("Average Document Length :",
      df["document"].str.len().mean())

Final Dataset Statistics
Total Documents : 657
Average Sanskrit Length : 97.59360730593608
Average Translation Length : 1621.0928462709285
Average Document Length : 1758.5220700152206

In [19]:
df.sample(5)

,unique_key,sanskrit_data,translation,document
389,390,द्यूतं छलयतामस्मि तेजस्तेजस्विनामहम् ।जयोऽस्मि...,There are many kinds of cheaters all over the ...,Verse ID: 390\n\nSanskrit:\nद्यूतं छलयतामस्मि ...
109,110,एषा ब्राह्मी स्थितिःपार्थ नैनां प्राप्य विमुह्...,One can attain Kṛṣṇa consciousness or divine l...,Verse ID: 110\n\nSanskrit:\nएषा ब्राह्मी स्थित...
152,153,एवं बुद्धेः परं बुद्ध्वा संस्तभ्यात्मानमात्मना...,This Third Chapter of the Bhagavad-gītā is con...,Verse ID: 153\n\nSanskrit:\nएवं बुद्धेः परं बु...
343,344,अनन्याश्चिन्तयन्तो मां ये जना: पर्युपासते ।तेष...,One who is unable to live for a moment without...,Verse ID: 344\n\nSanskrit:\nअनन्याश्चिन्तयन्तो...
625,626,स्वे स्वे कर्मण्यभिरत: संसिद्धिं लभते नरस्वकर्...,"By following his qualities of work, every man ...",Verse ID: 626\n\nSanskrit:\nस्वे स्वे कर्मण्यभ...