In [1]:
import pandas as pd
import random

random.seed(42)

In [2]:
pairs = pd.read_csv(r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\Training\query_pairs.csv")

print(pairs.shape)
pairs.head()

(3942, 3)

,query,document,label
0,What does this verse say?,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
1,Explain verse 137,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
2,Explain verse 326,Verse ID: 326\n\nSanskrit:\nमया ततमिदं सर्वं ज...,1
3,What does this verse say?,Verse ID: 547\n\nSanskrit:\nअनेकचित्तविभ्रान्त...,1
4,एतान्यपि तु कर्माणि सङ्गं त्यक्त्वा फलानि च ।क...,Verse ID: 587\n\nSanskrit:\nएतान्यपि तु कर्माण...,1

In [4]:
pairs['label'].unique()

array([1])

In [5]:
all_documents = pairs["document"].unique().tolist()

print("Unique documents :", len(all_documents))

Unique documents : 657

Create Triplets

In [6]:
triplets = []

for _, row in pairs.iterrows():

    anchor = row["query"]
    positive = row["document"]

    # choose a random document
    negative = random.choice(all_documents)

    # ensure negative != positive
    while negative == positive:
        negative = random.choice(all_documents)

    triplets.append({
        "anchor": anchor,
        "positive": positive,
        "negative": negative
    })

In [7]:
triplets_df = pd.DataFrame(triplets)

triplets_df.head()

,anchor,positive,negative
0,What does this verse say?,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,Verse ID: 67\n\nSanskrit:\nअव्यक्तादीनि भूतानि...
1,Explain verse 137,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,Verse ID: 182\n\nSanskrit:\nअपाने जुह्वति प्रा...
2,Explain verse 326,Verse ID: 326\n\nSanskrit:\nमया ततमिदं सर्वं ज...,Verse ID: 25\n\nSanskrit:\nअर्जुन उवाचदृष्ट्वे...
3,What does this verse say?,Verse ID: 547\n\nSanskrit:\nअनेकचित्तविभ्रान्त...,Verse ID: 174\n\nSanskrit:\nनिराशीर्यतचित्तात्...
4,एतान्यपि तु कर्माणि सङ्गं त्यक्त्वा फलानि च ।क...,Verse ID: 587\n\nSanskrit:\nएतान्यपि तु कर्माण...,Verse ID: 121\n\nSanskrit:\nदेवान्भावयतातेन ते...

In [8]:
triplets_df.to_csv(
    "C:\\Users\\Jasmin Babariya\\Downloads\\immverse.ai\\Task\\Data\\Training\\triplets.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Triplets saved successfully.")

Triplets saved successfully.

In [9]:
triplets_df.sample(5)

,anchor,positive,negative
2171,Explain verse 521,Verse ID: 521\n\nSanskrit:\nनिर्मानमोहा जितसङ्...,Verse ID: 573\n\nSanskrit:\nमूढग्राहेणात्मनो य...
3152,What is explained in verse 150?,Verse ID: 150\n\nSanskrit:\nइन्द्रियाणि मनो बु...,Verse ID: 258\n\nSanskrit:\nप्राप्य पुण्यकृतां...
1825,Explain verse 317,Verse ID: 317\n\nSanskrit:\nयत्र काले त्वनावृत...,Verse ID: 450\n\nSanskrit:\nश्रीभगवानुवाचमय्या...
2037,Meaning of verse 144,Verse ID: 144\n\nSanskrit:\nइन्द्रियस्येन्द्रि...,Verse ID: 174\n\nSanskrit:\nनिराशीर्यतचित्तात्...
3512,What does this verse say?,Verse ID: 653\n\nSanskrit:\nइत्यहं वासुदेवस्य ...,Verse ID: 471\n\nSanskrit:\nज्ञेयं यत्तत्प्रवक...

Check Negatives

In [10]:
wrong = (
    triplets_df["positive"] ==
    triplets_df["negative"]
).sum()

print("Incorrect Triplets :", wrong)

Incorrect Triplets : 0